# Generated by Django 5.2.17 on 2026-09-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0004_zonacomun_reservazona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(default='Sistema', max_length=150)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación')], max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='buildings.edificio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio',
                'verbose_name_plural': 'cambios',
                'ordering': ['-fecha', '-pk'],
                'indexes': [models.Index(fields=['edificio', '-fecha'], name='core_cambio_edif_fecha_idx'), models.Index(fields=['usuario', '-fecha'], name='core_cambio_usr_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('accion__in', ['CREAR', 'MODIFICAR', 'ELIMINAR'])), name='ck_cambio_accion_valida')],
            },
        ),
    ]
