# Generated by Django 5.2.17 on 2026-09-17 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('TESORERO', 'Tesorero'), ('JUNTA', 'Miembro de junta'), ('RESIDENTE', 'Residente')], max_length=13)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_autorizados', to='buildings.edificio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_edificios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario de edificio',
                'verbose_name_plural': 'usuarios de edificios',
                'ordering': ['edificio', 'usuario'],
                'indexes': [models.Index(fields=['edificio', 'rol', 'activo'], name='acc_usr_edif_rol_act_idx'), models.Index(fields=['usuario', 'activo'], name='acc_usr_usuario_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'edificio'), name='uq_usuario_edificio')],
            },
        ),
    ]
