# Generated by Django 5.2.17 on 2026-09-17 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuarioedificio',
            constraint=models.CheckConstraint(condition=models.Q(('rol__in', ['ADMINISTRADOR', 'TESORERO', 'JUNTA', 'RESIDENTE'])), name='ck_usuario_edif_rol_valido'),
        ),
    ]
