# Generated by Django 5.2.17 on 2026-09-17 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('telefono', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Introduce un teléfono válido de 7 a 25 caracteres; puede incluir espacios, guiones y paréntesis.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('correo', models.EmailField(max_length=254)),
                ('identificacion', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['nombre_completo', 'id'],
                'indexes': [models.Index(fields=['activo', 'nombre_completo'], name='ppl_pers_act_nom_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelacionApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('INQUILINO', 'Inquilino'), ('OCUPANTE', 'Ocupante')], max_length=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('puede_acceder_portal', models.BooleanField(default=False)),
                ('puede_ver_estado_cuenta', models.BooleanField(default=False)),
                ('puede_recibir_comunicaciones', models.BooleanField(default=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_personas', to='buildings.apartamento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_apartamento', to='people.persona')),
            ],
            options={
                'verbose_name': 'relación con apartamento',
                'verbose_name_plural': 'relaciones con apartamentos',
                'ordering': ['apartamento', '-fecha_inicio', 'persona'],
                'indexes': [models.Index(fields=['apartamento', 'tipo', 'fecha_finalizacion'], name='ppl_rel_apto_tipo_fin_idx'), models.Index(fields=['persona', 'fecha_finalizacion'], name='ppl_rel_pers_fin_idx')],
                'constraints': [models.UniqueConstraint(fields=('persona', 'apartamento', 'tipo', 'fecha_inicio'), name='uq_rel_persona_apto_tipo_inicio'), models.CheckConstraint(condition=models.Q(('fecha_finalizacion__isnull', True), ('fecha_finalizacion__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_rel_fechas_validas'), models.CheckConstraint(condition=models.Q(('puede_ver_estado_cuenta', False), ('puede_acceder_portal', True), _connector='OR'), name='ck_rel_estado_requiere_portal')],
            },
        ),
    ]
