# Generated by Django 5.2.17 on 2026-09-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relacionapartamento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['PROPIETARIO', 'INQUILINO', 'OCUPANTE'])), name='ck_rel_tipo_valido'),
        ),
    ]
