# Generated by Django 5.2.17 on 2026-09-17 00:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('direccion', models.TextField()),
                ('telefono_administrativo', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Introduce un teléfono válido de 7 a 25 caracteres; puede incluir espacios, guiones y paréntesis.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('correo_administrativo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'edificio',
                'verbose_name_plural': 'edificios',
                'ordering': ['nombre', 'id'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='bld_edif_act_nom_idx')],
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcentaje_contribucion', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Porcentaje entre 0 y 100 utilizado para distribuir gastos.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('peso_voto', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Peso de voto independiente del porcentaje de gastos.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartamentos', to='buildings.edificio')),
            ],
            options={
                'verbose_name': 'apartamento',
                'verbose_name_plural': 'apartamentos',
                'ordering': ['edificio__nombre', 'numero', 'id'],
                'indexes': [models.Index(fields=['edificio', 'activo'], name='bld_apto_edif_act_idx')],
                'constraints': [models.UniqueConstraint(models.F('edificio'), django.db.models.functions.text.Lower('numero'), name='uq_apto_edif_numero_ci'), models.CheckConstraint(condition=models.Q(('cuota_mensual__gte', 0)), name='ck_apto_cuota_no_neg'), models.CheckConstraint(condition=models.Q(('porcentaje_contribucion__gte', 0), ('porcentaje_contribucion__lte', 100)), name='ck_apto_porcentaje_rango'), models.CheckConstraint(condition=models.Q(('peso_voto__gte', 0)), name='ck_apto_peso_voto_no_neg')],
            },
        ),
    ]
